### ISSUE TITLE
Invoke-CommandAs

### ISSUE THREAD

**Issue by mkellerman** [littletoyrobots/EUCMonitoringRedux#1]
So? what did you find? ;)

**Comment by littletoyrobots** [comment]
I'm finally getting back around to putting some time into this.  I really dig that project, and especially want to play with the AsGMSA more, even if not in this project. 

The first idea was to use your -AsUser allow the telegraf service running as system user to store different credentials for different tasks, but I went crosseyed trying to nest the scriptblocks to store them not in plaintext, and that was before permissions got in the way.  

I'm currently trying to flesh out the other functionality and will hopefully circle back on it to see if there's a decent way of doing this.

**Comment by mkellerman** [comment]
Let me know if there is anything I can help implement in Invoke-CommandAs to help you accelerate your project!

**Comment by littletoyrobots** [comment]
Will do!  Thanks!
